Repository tmphat1312/IAI-search-project, pull requests merged in 2024-04, with the labels that each got.

#1 UI and bare bone
  .vscode/settings.json
  favicon.ico
  input.txt
  main.py
Labels: help wanted

#3 Chạy thuật toán thông qua tương tác với màn hình
  .vscode/settings.json
  input.txt
  main.py
Labels: enhancement

#5 a-star algorithm
  main.py
Labels: enhancement

#7 Update README file
  README.md
  docs/screenshot.png
Labels: documentation
